-- MySQL Script generated by MySQL Workbench
-- Wed Mar 29 11:12:58 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `netflix` DEFAULT CHARACTER SET utf8 ;
USE `netflix` ;

-- -----------------------------------------------------
-- Table `mydb`.`MOVIES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `movies` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NOT NULL,
  `genre` VARCHAR(45) NOT NULL,
  `image` VARCHAR(1000) NOT NULL,
  `category` VARCHAR(45) NOT NULL,
  `year` DATE NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`USERS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `users` (
  `idUser` INT NOT NULL AUTO_INCREMENT,
  `user` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `plan_details` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idUser`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ACTORS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `actors` (
  `idActor` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `lastname` VARCHAR(45) NOT NULL,
  `country` VARCHAR(45) NOT NULL,
  `birthday` DATE NOT NULL,
  PRIMARY KEY (`idActor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`rel_movie_actors`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rel_movie_actors` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `MOVIES_id` INT NOT NULL,
  `actors_idActor` INT NOT NULL,
  PRIMARY KEY (`id`, `movies_id`, `actors_idActor`),
  INDEX `fk_actors_has_movies_movies1_idx` (`movies_id` ASC) VISIBLE,
  INDEX `fk_actors_has_movies_actors_idx` (`actors_idActor` ASC) VISIBLE,
  CONSTRAINT `fk_actors_has_movies_actors`
    FOREIGN KEY (`actors_idActor`)
    REFERENCES `actors` (`idActor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_actors_has_movies_movies1`
    FOREIGN KEY (`movies_id`)
    REFERENCES `movies` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`rel_movies_users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rel_movies_users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `users_idUser` INT NOT NULL,
  `movies_id` INT NOT NULL,
  PRIMARY KEY (`id`, `users_idUser`, `movies_id`),
  INDEX `fk_users_has_movies_movies1_idx` (`movies_id` ASC) VISIBLE,
  INDEX `fk_users_has_movies_users1_idx` (`users_idUser` ASC) VISIBLE,
  CONSTRAINT `fk_users_has_movies_users1`
    FOREIGN KEY (`users_idUser`)
    REFERENCES `users` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_users_has_movies_movies1`
    FOREIGN KEY (`movies_id`)
    REFERENCES `movies` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
