-- MySQL Script generated by MySQL Workbench
-- Wed Mar 29 11:12:58 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`MOVIES`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`MOVIES` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(45) NOT NULL,
  `gender` VARCHAR(45) NOT NULL,
  `image` VARCHAR(1000) NOT NULL,
  `category` VARCHAR(45) NOT NULL,
  `year` DATE NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`USERS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`USERS` (
  `idUser` INT NOT NULL AUTO_INCREMENT,
  `user` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `plan_details` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idUser`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ACTORS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ACTORS` (
  `idActor` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `lastname` VARCHAR(45) NOT NULL,
  `country` VARCHAR(45) NOT NULL,
  `birthday` DATE NOT NULL,
  PRIMARY KEY (`idActor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`rel_movie_actors`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`rel_movie_actors` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `MOVIES_id` INT NOT NULL,
  `ACTORS_idActor` INT NOT NULL,
  PRIMARY KEY (`id`, `MOVIES_id`, `ACTORS_idActor`),
  INDEX `fk_ACTORS_has_MOVIES_MOVIES1_idx` (`MOVIES_id` ASC) VISIBLE,
  INDEX `fk_ACTORS_has_MOVIES_ACTORS_idx` (`ACTORS_idActor` ASC) VISIBLE,
  CONSTRAINT `fk_ACTORS_has_MOVIES_ACTORS`
    FOREIGN KEY (`ACTORS_idActor`)
    REFERENCES `mydb`.`ACTORS` (`idActor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ACTORS_has_MOVIES_MOVIES1`
    FOREIGN KEY (`MOVIES_id`)
    REFERENCES `mydb`.`MOVIES` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`rel_movies_users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`rel_movies_users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `USERS_idUser` INT NOT NULL,
  `MOVIES_id` INT NOT NULL,
  PRIMARY KEY (`id`, `USERS_idUser`, `MOVIES_id`),
  INDEX `fk_USERS_has_MOVIES_MOVIES1_idx` (`MOVIES_id` ASC) VISIBLE,
  INDEX `fk_USERS_has_MOVIES_USERS1_idx` (`USERS_idUser` ASC) VISIBLE,
  CONSTRAINT `fk_USERS_has_MOVIES_USERS1`
    FOREIGN KEY (`USERS_idUser`)
    REFERENCES `mydb`.`USERS` (`idUser`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_USERS_has_MOVIES_MOVIES1`
    FOREIGN KEY (`MOVIES_id`)
    REFERENCES `mydb`.`MOVIES` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
